services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Starfruit\ShopBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    Starfruit\ShopBundle\Model\:
        resource: '../src/Model'
        public: true

    Starfruit\ShopBundle\Extension\:
        resource: '../src/Extension'
        public: true

    Starfruit\ShopBundle\Service\:
        resource: '../src/Service'
        public: true

    # authentication login listener for updating e-commerce framework environment after login
    Starfruit\ShopBundle\EventListener\AuthenticationLoginListener: ~

# add more services, or override services that need manual wiring
#    Starfruit\ShopBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
